dist: trusty
sudo: required
branches:
  except: "/^v\\d/"
env:
  matrix:
  - DIST=precise
  - DIST=raring
  - DIST=trusty
  - DIST=vivid
  - DIST=xenial
  - DIST=zesty
before_install:
- sudo apt-get install build-essential debhelper devscripts dh-make lintian
- gem install asciidoctor
install: true
before_script: if [ "$TRAVIS_BRANCH" != "master" ]; then export SIGNING_OPTS="-uc -us"; fi
script: make deb
before_deploy: echo -e $GPG_SECRET | gpg --import
deploy:
- provider: script
  script: 'curl --fail --data "{ \"tag_name\": \"v$(make version)\",
    \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(make version)\"
  }" --user bot50:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
  on:
    branch: master
- provider: script
  script: dput ppa:cs50/ppa build/deb/*.changes
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
